name: CI/CD for Housing API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install flake8 pytest
          # Only API deps needed for import sanity; adjust if you have tests needing these
          pip install -r api/requirements.txt

      - name: Lint (flake8)
        run: flake8 api/ --ignore=E501

      - name: Run tests (pytest)
        run: pytest -q || true  # <-- keep green if you don’t have tests yet; remove '|| true' once you add tests

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.sagarpawar123 }}
          password: ${{ secrets.dckr_pat_kOgt5AYiPOqvXJdxlBBlAo8bEoQ }}

      - name: Build and push (latest & sha tags)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.sagarpawar123 }}/housing-api:latest
            ${{ secrets.dckr_pat_kOgt5AYiPOqvXJdxlBBlAo8bEoQ }}/housing-api:${{ github.sha }}
